Team-Panopticon/TBD-client

index.css, package.json, src/main.tsx, src/pages/MeetingCreate.tsx, src/pages/styled.tsx, src/theme.ts, yarn.lock
- CSS Reset 파일 적용
- Flex 기반의 Header, Contents, Footer 레이아웃 추가
- styled components 설치
- styled components 기반 테마 설정
=> 투표 생성 페이지 레이아웃 추가

.github/CODEOWNERS
- 자동 리뷰 등록을 위한 codeowner 설정 추가
=> codeowner 설정 추가

src/pages/MeetingCreate.tsx, src/templates/MeetingCreate/SelectMeetingType.tsx, src/templates/MeetingCreate/styled.tsx, src/theme.ts
- MUI ToggleButton theme 커스텀 설정
컴포넌트의 기본 스타일을 수정하기 위해 커스텀 설정
- SelectMeetingType 컴포넌트 추가
ToggleButton의 기본 border 관련 스타일을 변경하기 위해 inline style 수정(styled component 사용 시 우선순위에 의해 수정 불가)
closes #17
=> MeetingCreate 페이지 SelectMeetingType 컴포넌트 추가

src/GlobalStyle.ts, src/main.tsx
우선은 reset css보다는 그냥 간단하게 3가지 속성만 지정해줬습니다.
후에 필요하다면 reset css를 넣는것도 좋을 것 같아요.
- box-sizing
- margin:0 
- padding:0
=> feat: 글로벌 css 추가

src/components/MaskingInput.tsx, src/styled.d.ts
비밀번호 입력용 마스킹 인풋입니다.
copilot의 도움을 적극적으로 받아봤습니다.
theme의 타입을 사용하기 위해 삭제했던 styled.d.ts를 부활시켰습니다.
=> masking input 컴포넌트 추가

src/components/Chip/Chip.tsx, src/components/Chip/styled.ts
close #36 
- 커스텀으로 Chip 컴포넌트를 바꿨습니다.
- Chip은 focus, checked를 받아서 따로 스타일이 적용될 수 있도록 했습니다.
- 캘린더랑 비슷하게 거의 컴포넌트를 쓰는데, border라던지 배경색, height가 조금씩 다른데 이것까지 쓸 수 있게 처리를 해야할까 고민입니다..
=> UserChip 컴포넌트 추가

package.json, src/pages/MeetingCreate.tsx, src/stores/createMeeting.ts, src/templates/MeetingCreate/Calender.tsx, src/templates/MeetingCreate/SelectDates.tsx, yarn.lock
- SelectDates 컴포넌트 추가
- mui StaticDatePicker를 여러 날짜를 선택할 수 있도록 커스텀
- meeting.dates 상태 타입 변경 (string -> Dayjs)
=> SelectDates 컴포넌트 추가

package.json, src/apis/instance.ts, src/apis/meetings.ts, src/apis/types.ts, yarn.lock
- Axios 세팅
- createMeeting API 추가
=> Axios 세팅 및 createMeeting API 추가

.env.development, .env.production
- local 경로: firebase emulator의 경로
- production 경로: firebase functions의 경로
- API 경로는 비밀정보가 아닌 것으로 간주하고, git에 업로드되는 파일에 포함
=> local, production API 호출경로 추가

src/components/MaskingInput.tsx, src/styled.d.ts, src/templates/MeetingCreate/InputPasswordModal.tsx, src/templates/MeetingCreate/MeetingEditTemplate.tsx, src/templates/MeetingCreate/styled.tsx, src/theme.ts
- 모임 생성하기 비밀번호 설정 modal 추가
- mui CustomPalette 추가, transPrimary 색상 추가
=> 모임 생성하기 비밀번호 설정 modal 추가

src/stores/createMeeting.ts, src/stores/localstorageEffect.ts, src/stores/user.ts
- 초기 url 진입시 사용자 id 확인을 위한 localstorageEffect 를 추가했습니다.
- user interface는 샘플입니다.
=> feat: 로컬스토리지 사용을 위한  localStorageEffect 추가

src/pages/MeetingView.tsx
- 보기모드, 투표모드 모두 MeetingView 컴포넌트 안에서 동작 필요
=> feat: MeetingView 페이지 구조 세팅

src/apis/users.ts, src/components/VoteTable/VoteTable.tsx, src/hooks/useMeetingViewVoteMode.ts, src/pages/MeetingView.tsx
- VoteTable은 최초 디자인과 동일하게 view만을 담당하는 역할로 남김
- useMeetingViewVoteMode hook에서 투표 보기 페이지 > 투표 모드에서 필요한 상태 및 핸들러 관리
- feature/view-mode와 동일한 구조를 사용
=> 투표 보기 페이지 > 투표 모드에서 VoteTable 클릭 로직을 hook으로 분리하여 구현

src/apis/users.ts, src/components/VoteTable/VoteTable.tsx, src/hooks/useMeetingView.ts, src/pages/MeetingView.tsx
- useMeetingView 
- 훅에서 recoil에서 가져온 데이터를 로컬 상태로 가지게 구현
- 현재 focused, checked 여부를 저장해야해서 로컬 상태로 가지도록 했습니다.
-  각 테이블, 유저리스트를 클릭 시 현재 데이터에 연결된 데이터들이 표시될 수 있도록 구현했습니다.
=> 투표 보기 페이지 > 보기 모드에서 VoteTable, UserList 클릭 시 현재 선택한 데이터에 대해서 표시될 수 있도록 구현

src/hooks/useMeetingView.ts, src/hooks/useMeetingViewVoteMode.ts, src/pages/MeetingView.tsx
- 기존에 있던 훅에서 slot을 사용할 수 있는 형태로 핸들러 변경
=> MeetingView 페이지 구현

src/main.tsx, src/mocks/handlers.ts, src/mocks/index.ts, src/mocks/votingsData.ts
- userData -> votingsData로 네이밍을 변경
- name -> username 변경
- votings 데이터를 객체 형식에서 배열 형식으로 변경
=> mock 서버 voting 데이터타입 수정

src/apis/votes.ts, src/mocks/meetingData.ts, src/mocks/votingsData.ts
- votings, meetings 목 데이터에 타입을 추가하고, 타입에 맞게 데이터를 수정했습니다.
=> feat: votings, meetings mock 데이터에 타입 추가 후 타입에 맞게 수정

package.json, src/main.tsx
- `yarn local`: MSW를 사용하여 development env로 실행
- `yarn prod`: production env로 실행
=> feat: local(msw), prod 개발 명령어 추가

src/pages/MeetingView.tsx, src/pages/MeetingVote.tsx
- 보기모드에서 사용하지 않는 비밀번호 모달 삭제
- 보기모드에서 msw를 사용하던 부분을 params의 meetingId를 바라보도록 수정
- 투표모드에서 투표 성공 후 보기모드로 갈 수 있도록 수정
=> feat: Meeting 생성, 투표모드, 보기모드 페이지에 api 연결

src/pages/MeetingView.tsx
- 유저 여부에 따라서 하단 텍스트가 '다시 투표하러 가기' 또는 '투표하러 가기'가 될 수 있도록 추가
close #67
=> feat: 유저 여부에 따라서 하단 버튼 텍스트가 변경될 수 있도록 추가

src/components/VoteTable/VoteTable.tsx, src/hooks/useMeetingView.ts, src/hooks/useMeetingVote.ts, src/mocks/meetingData.ts, src/pages/MeetingView.tsx, src/pages/MeetingVote.tsx, src/stores/voting.ts
- VoteTableVoting에 mealType 추가
votingSlot에 mealType 정보를 가지고 있어야 슬롯 클릭 시 mealType 비교가 가능하므로 추가
- useMeetingView / useMeetingVote에서 meetingType 에 대해서 분기처리하여 mealType일 경우도 처리 가능하도록 추가
- checked, current가 meetingType에 따라서 계산되도록 수정
=> voteTable mealType의 경우에도 voteSlot 클릭이 동작하도록 수정

src/components/ShareDialog.tsx, src/pages/MeetingResult.tsx
- resultpage에 적용
- 공통으로 사용하기 위해
- 추후 전역 관리로 이동하는것이 좋아보임
=> feat: shareDialog 추가

src/pages/MeetingVote.tsx, src/templates/MeetingView/InputUsernameModal.tsx
- username이 invalid한 경우 완료 버튼 disable
#104 
- ~~currentUserVoting이 invalid한 경우 투표하기 버튼 disable~~
=> username이 invalid한 경우 버튼 disable

src/templates/MeetingView/InputUsernameModal.tsx
- 유저 닉네임 입력 시 20까지 입력할 수 있도록 했습니다.
close #119
=> feat: 닉네임을 20자로 제한

.env.production
- env파일에 v1추가
- 사실 이렇게 하는거보다 axios instance 만드는 곳에서 v1,v2 instance를 만들어서 사용하는 것이 좋을 것 같은데, interceptor에서 progress를 띄워주는 것 때문에 좀 더 고민해봐야할 것 같아서 우선 임시방편으로 env파일에 추가해줬습니다!
=> feat: env파일에 v1 추가

src/apis/meetings.ts, src/apis/types.ts, src/hooks/useMeetingResult.ts, src/hooks/useMeetingView.ts, src/hooks/useMeetingVote.ts, src/mocks/meetingData.ts, src/pages/MeetingResult.tsx, src/pages/MeetingView.tsx, src/pages/MeetingVote.tsx, src/stores/voting.ts
- CreateMeetingResponse, GetMeetingResponse 타입을 MeetingResponse 타입으로 통일
- MeetingResponse에서 dates의 타입이 dayjs인 Meeting 타입 추가
=> 서버의 Meeting 응답에 적용되는 타입 통일

.env.development, .env.production, index.html, src/apis/instance.ts, src/components/KakaoShareButton.tsx, src/components/ShareButton.tsx, src/components/ShareDialog.tsx, src/hooks/useKakaoShare.ts, src/mocks/handlers.ts, src/pages/MeetingResult.tsx, src/pages/MeetingView.tsx, src/vite-env.d.ts
- 카카오톡 sdk 스크립트를 추가
- 카카오톡 공유하기 버튼 구현
- 참고)
- 크롬 개발자도구로 모바일로 키면 앱을 다운로드하라고 나오는데, 데스크탑으로 하면 카카오톡이 깔려 있으면 카카오톡이 열립니다!
- 프리뷰로는 확인하기 힘들것 같습니다.(카카오 플랫폼에서 지정한 도메인만 가능해요..)
- 현재는 motoo.day, localhost:5173으로 해두었습니다.
=> feat: 카카오톡 공유하기 버튼을 추가

src/pages/MeetingView.tsx, src/pages/MeetingVote.tsx
투표 페이지 - 로딩 바가 2번 끊어서 보여짐 #152
--
TEST
- 보기 페이지
- 투표 페이지 
- 에서 로딩바가 두번 생성되는지 확인
close #152
=> fix: 모임 보기 , 투표 페이지에서 로딩 두번 발생하는 현상

src/components/MaskingInput.tsx, src/templates/MeetingView/InputUsernameModal.tsx
fix: autocomplete = off
close #157
=> fix: autocomplete = off

src/hooks/useMeetingView.ts
- 투표된 슬롯이 없는 경우에도 checked, focused 될 수 있도록 코드의 위치를 수정했습니다.
close #160
=> fix: 유저 클릭 시 투표된 slot이 없더라도 checked가 변할 수 있도록 타이밍 변경

.env.development, src/components/UserList/UserList.tsx, src/main.tsx, src/pages/MeetingConfirm.tsx, src/pages/MeetingView.tsx, src/pages/MeetingVote.tsx
userList 컴포넌트의 placeholder 텍스트의 기본값을 추가했습니다.
#165
=> fix: userlist placeholder의 기본값 추가

package.json, src/components/VoteTable/VoteTable.tsx, yarn.lock
브라우저 환경 체크를 위해
react-device-detect
를 설치했습니다.
추후 @junsushin-dev 님이 적용하신 방식과 통일하면 될것같습니다.
close #179
=> 모바일 환경에서 빠르게 클릭시 중간중간 클릭이 안되는 현상

src/templates/MeetingEdit/MeetingEditTemplate.tsx, src/utils/hasTouchScreen.ts
closes #147 
- 모바일 브라우저 detection을 위해서 hasTouchScreen 유틸 추가
- 모바일에서 onBlur 이벤트 발생 시  step으로 이동시킴
https://github.com/Team-Panopticon/TBD-client/assets/32405358/c2f46285-1e73-4f7e-b657-8e2efecc3700
=> 미팅 생성 페이지 > 모바일 브라우저의 virtual keyboard에서 Done(완료) 클릭 시 다음 step으로 이동

src/templates/MeetingEdit/MeetingEditTemplate.tsx
=> 모임 수정 페이지에 다음에하기 버튼 추가

src/hooks/useRestartAnimation.ts, src/templates/MeetingEdit/MeetingEditTemplate.tsx, src/templates/MeetingEdit/styled.tsx
- 타이틀에 애니메이션을 추가해줬습니다.
- 애니메이션 재시작을 위해서 커스텀 훅을 추가했습니다
- 참고 : https://www.kirupa.com/animations/restarting_css_animations.htm
close #146
=> feat: 모임 생성 타이틀에 애니메이션 추가

src/components/VoteTable/VoteTable.tsx, src/hooks/useMeetingVote.ts, src/pages/MeetingConfirm.tsx, src/pages/MeetingView.tsx, src/pages/MeetingVote.tsx
closes #156 
- 점심, 저녁 모드에서 날짜칸 클릭으로 한번에 2개 모두 선택할 수 있도록 기능추가
- 점심, 저녁 중 0개 선택되어있는 경우에는 모두 선택된 상태로 변경
- 점심, 저녁 중 1개 선택되어있는 경우에는 모두 선택된 상태로 변경
- 점심, 저녁 중 2개 선택되어있는 경우에는 모두 미선택된 상태로 변경
- Click Handler 구별하기 위해서 기존 onClick 을 onSlotClick으로 이름 변경
=> 투표 페이지에서 날짜 클릭 시 점심, 저녁 모두 투표되도록 기능추가

src/pages/MeetingView.tsx, src/templates/MeetingView/Dropdown/Dropdown.tsx, src/templates/MeetingView/Dropdown/styled.tsx
=> MeetingView 페이지에서 설정버튼이 있어도 타이틀이 중앙정렬 되도록 수정

src/components/ShareDialog/ShareDialog.tsx, src/hooks/useKakaoShare.ts
closes #167 
- clipboard API가 특정 환경에서 동작하지 않아 execCommand로 변경
=> 공유하기 기능을 clipboard API가 아닌 execCommand("copy")를 사용하도록 변경

index.html
closes #208 
- script 실행 순서 상 kakao SDK script가 main.tsx chunk 보다 먼저 위치하도록 조정
- main.tsx chunk 실행 시 window.Kakao 객체에서 NPE 에러가 나지 않음
- main.tsx chunk는 <script type="module"> 이라서 기본적으로 defer가 적용되며, 따라서 kakao -> main 순서 보장됨
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#defer
=> main.tsx 실행 시점에 kakao SDK가 window에 주입되어 있도록 보장

package.json, src/pages/MeetingConfirm.tsx, yarn.lock
- react-query 타입 추론에 버그가 있어서 버전을 올렸습니다.
- mutate후 캐시를 무효화하고 결과 페이지로 이동할 수 있게 수정했습니다.
close #213
=> fix: 미팅 확정 후 캐시를 무효화 시키고 result 페이지로 이동하게 수정

src/hooks/useMeetingVote.ts
closes #222 
- 날짜타입에서는 날짜 클릭 시 날짜만 있는 slot을 추가하도록 변경
=> 날짜타입 & 투표모드에서 날짜칸 클릭시 lunch, dinner 정보 들어가는 것 수정

src/pages/MeetingResult.tsx, src/templates/MeetingView/CheckConfirmModal.tsx, src/utils/getMealLabel.ts
=> 모임 확정결과 페이지에서 점심 / 저녁 여부를 표시

src/components/ShareDialog/ShareDialog.tsx, src/pages/MeetingVote.tsx
closes #218 
공유링크에 ref=share 붙여서 제공
진입 시 localstorage에 값 있는경우(=기존유저인 경우) 보기모드 페이지로 이동
=> 한번 투표했던 유저가 공유링크로 재접속 하는경우 보기 페이지로 이동

index.css, index.html, src/components/VoteTable/VoteTable.tsx, src/main.tsx
closes #217 
- 스크롤 시 touch로 날짜 선택이 되는 이슈 해결
- 빠르게 두번 클릭 시 양쪽 칸이 한번씩 클릭되는게 아니라 처음 칸에 두번 클릭되는 이슈 해결
=> 더블클릭으로 이슈 발생하는지 테스트

src/templates/MeetingView/Dropdown/Dropdown.tsx, src/templates/MeetingView/Dropdown/styled.tsx
drawer 를 하단 버튼으로 수정했습니다.
close #220
=> feat: 확정 드롭다운 drawer로 변경

src/hooks/useMeetingResult.ts
=> feat: 미팅 결과  비교시, meal타입도 고려

src/components/Chip/Chip.tsx, src/components/UserList/UserList.tsx, src/pages/MeetingVote.tsx
closes #245 
- 페이지 접속 시 선택된 항목에 대해서 최초 1회 가이드 툴팁 노출
- 화면 아무데나 클릭할 경우 툴팁 사라짐
https://github.com/Team-Panopticon/TBD-client/assets/32405358/7522b6cc-37a3-4db4-873c-aace3f3a5c48
=> 투표페이지에서 유저선택 해제 가이드 툴팁 추가

src/components/Calendar.tsx, src/components/styled.tsx, src/templates/MeetingEdit/SelectDates.tsx
달력컴포넌트 큼지막하게 만들어서 추가해보았습니다.
나중에 스와이프등이 제공되면 좋을것 같습니다.
=> Feat: 달력 컴포넌트 생성

src/components/buttons/ResultPageButton.tsx, src/components/buttons/VotePageButton.tsx, src/components/pageLayout.tsx, src/components/styled.tsx, src/pages/MeetingConfirm.tsx, src/pages/MeetingResult.tsx, src/pages/MeetingView.tsx, src/pages/MeetingVote.tsx, src/templates/MeetingEdit/CreatePasswordModal.tsx, src/templates/MeetingEdit/MeetingEditTemplate.tsx, src/templates/MeetingEdit/styled.tsx, src/templates/MeetingView/InputPasswordModal.tsx, src/templates/MeetingView/InputUsernameModal.tsx
머지 이슈로 develop에 반영되지 않아 PR 재생성
#247
=> 하단 버튼 UI 변경 (여백 추가 & 라운드 처리)

src/apis/instance.ts, src/apis/meetings.ts, src/app.tsx, src/hooks/useMeetingData.ts, src/hooks/useProgress.ts, src/pages/MeetingConfirm.tsx, src/pages/MeetingCreate.tsx, src/pages/MeetingModify.tsx, src/pages/MeetingResult.tsx, src/pages/MeetingView.tsx, src/pages/MeetingVote.tsx, src/templates/MeetingView/InputPasswordModal.tsx, src/templates/MeetingView/InputUsernameModal.tsx
- api 사용 부분을 react-query로 모두 수정했어요
close #251
=> refactor: api사용 부분을 리액트 쿼리를 이용해서 수정

src/hooks/MeetingView/useMeetingViewContents.ts, src/hooks/MeetingView/useMeetingViewFooter.ts, src/pages/MeetingView/MeetingView.tsx, src/templates/MeetingView/MeetingViewContents/index.tsx, src/templates/MeetingView/MeetingViewFooter/index.tsx
- MeetingView의 Contents에 해당하는 부분을 따로 컴포넌트로 분리했습니다.
- MeetingView의 Footer에 해당하는 부분을 따로 컴포넌트로 분리했습니다.
- 브랜치 이름과 맞지 않지만, 작업 내용이 거의 비슷하고 간단하여 합쳤어요.
- changes는 좀 많지만 기존에있던 것을 이름을 바꾸거나 복붙한 느낌이라서 하나의 mr로 올렸습니다.
=> feat: MeetingView에 있던 Contents를 컴포넌트로 분리

src/hooks/MeetingResult/useMeetingResultContents.ts, src/hooks/MeetingResult/useMeetingResultFooter.ts, src/hooks/MeetingResult/useMeetingResultHeader.ts, src/pages/MeetingResult/MeetingResult.tsx, src/templates/MeetingResult/MeetingResultContents/index.tsx, src/templates/MeetingResult/MeetingResultFooter/index.tsx, src/templates/MeetingResult/MeetingResultHeader/index.tsx
- MeetingResult 페이지를 header,contents,footer 컴포넌트로 분리했어요
=> MeetingResult 페이지를 header,contents,footer 컴포넌트로 분리

src/hooks/MeetingView/useMeetingViewHeader.ts, src/pages/MeetingView/MeetingView.tsx, src/templates/MeetingView/MeetingViewHeader/index.tsx
- MeetingView에서 header에 해당하는 부분을 따로 컴포넌트로 분리했어요.
=> MeetingView에서 header에 해당하는 부분을 따로 컴포넌트로 분리

src/hooks/MeetingConfirm/useMeetingConfirmContents.ts, src/hooks/MeetingResult/useMeetingResultContents.ts, src/hooks/MeetingView/useMeetingViewContents.ts, src/hooks/MeetingVote/useMeetingVoteContents.ts, src/hooks/MeetingVote/useMeetingVoteFooter.ts, src/hooks/MeetingVote/useMeetingVoteHeader.ts, src/hooks/useMeetingView.ts, src/pages/MeetingVote/MeetingVote.tsx, src/templates/MeetingVote/MeetingVoteContents/index.tsx, src/templates/MeetingVote/MeetingVoteFooter/index.tsx, src/templates/MeetingVote/MeetingVoteHeader/index.tsx
- MeetingView와 마찬가지로, header, contents, footer로 분리했어요.
- 변경사항이 많긴 하지만, 이전 MeetingView mr과 거의 유사한 작업이라서 하나의 mr에서 했습니다 :)
=> MeetingVote 컴포넌트를 header, contents, footer로 분리

src/app.tsx, src/hooks/MeetingConfirm/useMeetingConfirmFooter.ts, src/hooks/MeetingView/useMeetingViewHeader.ts, src/hooks/MeetingVote/useMeetingVoteFooter.ts, src/pages/MeetingCreate/MeetingCreate.tsx, src/pages/MeetingModify/MeetingModify.tsx, src/templates/MeetingView/InputPasswordModal.tsx
- reactQuery의 공통 로직인 에러 처리를 defaultOption으로 설정
- reqctQuery의 onMutate, onSettled의 progress show/hide 처리를 defaultOption으로 설정
closes #261
=> reactQuery의 공통 로직인 에러처리, progress 처리를 defaultOption으로 설정

src/components/routes/RedirectIfConfirmedRoute.tsx, src/components/routes/RedirectIfInProgressRoute.tsx
- meeting 서버 정보를 가져올 때 쿼리키를 잘못 세팅한 것을 수정
=> fix: 쿼리키를 잘못 세팅한 것을 수정

src/components/MeetingContentsSkeleton.tsx, src/components/Progress.tsx, src/hooks/MeetingConfirm/useMeetingConfirmContents.ts, src/hooks/MeetingResult/useMeetingResultContents.ts, src/hooks/MeetingView/useMeetingViewContents.ts, src/hooks/MeetingVote/useMeetingVoteContents.ts, src/pages/MeetingConfirm/MeetingConfirm.tsx, src/pages/MeetingResult/MeetingResult.tsx, src/pages/MeetingView/MeetingView.tsx, src/pages/MeetingVote/MeetingVote.tsx, src/templates/MeetingConfirm/MeetingConfirmContents/index.tsx, src/templates/MeetingConfirm/MeetingConfirmHeader/index.tsx, src/templates/MeetingResult/MeetingResultContents/MeetingResultContentsSkeleton.tsx, src/templates/MeetingResult/MeetingResultContents/index.tsx, src/templates/MeetingView/MeetingViewContents/MeetingViewContentsSkeleton.tsx, src/templates/MeetingView/MeetingViewContents/index.tsx, src/templates/MeetingView/MeetingViewHeader/index.tsx, src/templates/MeetingVote/MeetingVoteContents/index.tsx, src/templates/MeetingVote/MeetingVoteHeader/index.tsx
- 각 페이지에 스켈레톤을 적용했어요.
- MeetingVote, view, confirm은 똑같고 result만 다릅니다 :)
=> feat: 각 페이지에 스켈레톤 적용

src/components/Header.tsx, src/pages/MeetingCreate/MeetingCreate.tsx
- 모임을 만든 후 모임을 새로 만드는 경우 상태 초기화가 될 수 있도록 했습니다.
close #281
=> fix: 모임 새로 만들기 시 미팅상태 스토어 초기화

src/components/styled.tsx
=> fix: calendar default color black
