package.json
src/components/DateInput.tsx
src/pages/MeetingCreate.tsx
yarn.lock

closes #18 
- dayjs
- 날짜를 편하게 처리하기 위해 dayjs를 사용했습니다
- 2kb 밖에 안되는 라이브러리이고 저희가 시간관련해서 딱히 대단한 기능을 사용하지 않을 것이라서 간단한것으로..
- 스타일을 맞추기 위해서 mui TextField 컴포넌트를 사용
- input type='date'로 작동하게 끔 구현
- mui에서 min, max가 없어서, inputRef를 이용해서 min, max를 처리
---
**스크린샷**

feat: DateInput 컴포넌트 구현

---

.eslintrc.cjs
package.json
yarn.lock

- 기존 '@typescript-eslint/no-unused-vars' 옵션은 off하고 플러그인에서 on 해야하는거 같아요.
- 안쓰는 변수의 경우는 지워주지 않고 warning 혹은 error가 가능해요
- 안쓰는 import는 자동 삭제해줍니다.

chore: eslint-plugin-unused-imports 설치 및 적용

---

.env.development
src/apis/meetings.ts
src/components/DateInput.tsx
src/pages/MeetingCreate.tsx
src/stores/createMeeting.ts
src/templates/MeetingEdit/InputPasswordModal.tsx
src/templates/MeetingEdit/MeetingEditTemplate.tsx

closes #59 
- meetingName에 대한 input 컴포넌트 자체의 validation 추가
- 다른 컴포넌트는 validation이 불필요하거나 컴포넌트 자체에 이미 내장되어 있음
- 각 step 별로 validation 결과에 따라서 '다음'버튼 활성화
- 미입력 상태는 undefined 값으로 구분하여 잘못입력된 빈 값과 구분함
- 지금은 현재 Step이 검증되면 `다음` 버튼이 활성화되도록 처리했으나, 지나간 Step도 수정이 가능하기 때문에 로직 상 지금까지의 Step이 모두 검증되어야 `다음` 버튼을 활성화시켜야 할 것 같습니다. 
- Step별로 input의 검증상태를 유지하고, 이를 Step 단계에 따라서 종합하여 disable 여부를 판단해야 하는데 어떻게 로직을 넣어야 할지 좋은 아이디어 있으시면 코멘트 부탁드립니다.

Create Meeting 페이지 input validation 추가

---

src/components/CenterContentModal.tsx
src/pages/MeetingView.tsx
src/templates/MeetingEdit/InputPasswordModal.tsx
src/templates/MeetingEdit/styled.tsx
src/templates/MeetingView/InputUsernameModal.tsx

- InputPasswordModal 리팩토링
mui Modal의 중앙에 컴포넌트를 적용할 수 있도록 스타일 요소를 `CenterContentModal` 컴포넌트로 분리
- username 입력 모달 추가
- viewmode 변경, 투표 완료 버튼 시 username 입력 모달 보이는 기능 추가
기본이 view 모드이고 투표모드로 변경하여 모달을 테스트해볼 수 있도록 기능 추가

username 입력 모달 추가

---

src/apis/users.ts
src/app.tsx
src/hooks/useMeetingViewVoteMode.ts
src/pages/MeetingView.tsx
src/pages/MeetingVote.tsx

closes #75 
- MeetingVote 페이지 분리 및 불필요한 변수, hook 제거
- 신규 route path 추가 및 MeetingVote 페이지 등록
- 선택된 유저가 없을 경우 toast 노출
- meetingId 값을 path param으로 사용
- 보기모드로 전환 기능
- 날짜 focus 기능 제거

MeetingView 페이지에서 MeetingVote 페이지를 별도로 분리

---

src/components/VoteTable/VoteTable.tsx
src/components/VoteTable/styled.tsx

- 투표 상태를 투명도로 표시했습니다.
- 투명도가 80퍼센트 이상인 경우 글자를 흰색으로 바꿉니다.
close #94

feat: 투표 상태를 투명도로 표시

---

src/components/UserList/UserList.tsx
src/hooks/useMeetingVote.ts
src/pages/MeetingVote.tsx
src/stores/currentUser.ts
src/stores/currentUserVotingSlots.ts
src/stores/voting.ts

closes #76 
- MeetingVote 페이지에서 UserList 클릭을 통해서 신규유저 <-> 기존유저 전환기능
- 기존유저가 선택된 상태에서 유저 선택 시 토글되어 신규 유저로 전환
- 기존유저로 전환 시 DB에 저장된 투표상태로 currentUserVotingSlots 초기화
- 신규유저로 전환 시 currentUserVotingSlots를 빈 배열로 전환

Vote 페이지에서 신규유저 <-> 기존유저 전환 기능 추가

---

package.json
src/app.tsx
src/components/ProtectedAdminRoute.tsx
src/components/pageLayout.tsx
src/main.tsx
src/pages/MeetingConfirm.tsx
src/templates/MeetingView/CheckConfirmModal.tsx
yarn.lock

- 모임시간을 골라서 확정하는 UX로 변경됨에 따라서 모임시간 확정 페이지 추가 필요
- 모임시간 slot 선택 시 참석자 hightlight
- 모임시간 확정하기 버튼 클릭 시 확정안내 팝업 노출
- admin 로그인이 안되어있는 경우 보기 페이지나 신규 페이지로 redirect 하도록 권한처리

MeetingConfirm 페이지 추가

---

src/apis/meetings.ts

- slot이 이미 객체이므로 그대로 전달되도록 `{ slot }` -> `slot`으로 수정
https://github.com/Team-Panopticon/TBD-server/pull/37

confirmMeeting API 시 slot을 객체로 다시 감싸지 않도록 수정

---

src/app.tsx
src/hooks/useMeetingVote.ts
src/pages/MeetingView.tsx
src/pages/MeetingVote.tsx
src/stores/currentUser.ts
src/templates/MeetingView/InputUsernameModal.tsx

- 자체 데모하면서 나온 투표페이지 로직 오류 수정
- #114 
- 스타일 작업은 #111 머지된 이후에 수정
1. ~~미리 투표 인원수를 1 늘려놓는다~~
2. 투표한 날짜에만 인원수와 투표수를 1씩 늘려놓는다
3. ~~아예 반영하지 않는다 (버튼 색상만 반영)~~

투표 페이지 로직 오류 수정

---

index.css
src/pages/MeetingConfirm.tsx
src/pages/MeetingView.tsx
src/pages/MeetingVote.tsx

- 보기, 투표하기 페이지와 헤더, 아이콘, 참석자목록, 테이블 스타일 통일
- 아이콘은 figma에 정의된 것이 없어서 MUI에서 적당한 아이콘을 가져왔습니다. 혹시 다른 아이콘 선호하시는 것 있으면 말씀부탁드려요. 
- MUI 컴포넌트에만 적용되던 Roboto 폰트를 모든 DOM 요소에 글로벌로 적용

투표확정 페이지 스타일 적용

---

src/components/ShareDialog/ShareDialog.tsx
src/hooks/useMeetingEdit.ts
src/pages/MeetingCreate.tsx
src/stores/createMeeting.ts
src/templates/MeetingEdit/MeetingEditTemplate.tsx

모임 생성 - 모임 이름으로 공백을 설정못하도록 & 공백에 대한 처리 추가 #151
--
TEST
- 모임 생성 > 모임이름 옆 최대 길이 표시
- 모임 생성 > 모임 이름 최대길이 30 이상 입력 불가
- 모임 생성 > trim된 모임이름으로 모임 생성
close #151

fix: 모임 이름 공백 제거

---

src/components/VoteTable/VoteTable.tsx

- DB, 서버쪽에서 데이터를 보낼 때 정렬해서 보내지 않고 있음
- 프론트에서 vote table 노출 시 데이터 정렬해서 표시

fix: VoteTable에서 날짜별 row를 정렬해서 노출

---

src/components/UserList/styled.ts
src/templates/MeetingView/InputUsernameModal.tsx

투표 페이지 - 투표모드 - 유저 명 공백 처리, trim 적용 #159
투표 페이지 - 투표 현황 유저 이름이 길 경우 UI가 깨짐 #153
-- TEST
투표모드 > 유저 이름 한글로 길게 입력 > chip 말줄임표 처리
투표모드 > 유저이름 앞뒤로 공백입력 > trim 처리된 유저 이름 등록
close #159 , #153

투표 페이지 - 투표모드 - 유저 명 공백 처리, trim 적용 ,  투표 현황 유저 이름이 길 경우 UI가 깨짐 

---

src/apis/meetings.ts
src/apis/types.ts
src/hooks/useMeetingResult.ts
src/pages/MeetingResult.tsx
src/stores/voting.ts

- 실제 데이터로 확정날짜, 요일이 표시되도록 했습니다.
- 실제 데이터로 참석 가능,불가능 유저 리스트가 표시되도록 했습니다.
- seletor를 없애고 useMeetingResult 훅에서 Meeting 데이터 기준으로 filtering 해줬습니다.
close #166

fix: 확정페이지에서 목데이터가 아닌 실제 데이터랑 연동

---

src/main.tsx

- reactQuery의 queryClient에 refetchOnWindowFocus 옵션을 false로 전역 설정되도록 추가
수정하기 페이지에서 focus를 다시 얻었을 때 서버 데이터를 다시 받아오며 수정 사항이 초기화되는 이슈 수정
close #183

reactQuery refetchOnWindowFocus 옵션 false 전역 설정 추가

---

src/templates/MeetingEdit/MeetingEditTemplate.tsx

- 모바일에서 done 버튼 혹은 블러 처리 되는 경우에 미팅 이름에 대한 밸리데이션을 하도록 추가했습니다.

fix: 모바일 done 클릭 시 미팅 이름에 대한 밸리데이션이 필요하도록 수정

---

src/components/ShareDialog/ShareDialog.tsx

클립보드 복사 성공 메시지를 alert에서 toast 메시지로 변경

---

src/components/CenterContentModal.tsx
src/components/MaskingInput.tsx

- 패스워드 4자리 입력시 자동 닫힘
- 모바일 키보드에 패스워드창이 가리는 문제 때문에 패스워드창 위치를 살짝 상단으로 이동
close #177 #199

패스워드 4자리 입력시 자동 닫힘,패스워드창 위치

---

package.json
src/pages/MeetingConfirm.tsx
yarn.lock

closes #204 
- local -> develop 브랜치와 motoo.day 모두 확정페이지 렌더링이 안되고 있음
- react-query v4에서 API 요청을 보내지 않고 있음
- 원인: Mac Chrome에서 navigator.onLine이 오프라인 상태가 아님에도 false로 설정되어 react query가 API 호출을 하지않는 이슈
- https://stackoverflow.com/questions/75538301/reactquery-queryfn-passed-to-usequery-is-never-run-happens-only-on-chrome
- react-query v5로 업데이트 시 정상 작동하는 것 확인되어 수정

모임날짜 확정 페이지가 렌더링되지 않는 이슈 해결

---

index.html
src/app.tsx

closes #198 
- index.html에 progress UI 추가
- material ui의 progress 스타일을 그대로 적용
- react가 그리는 root div에 progress를 그려 root div에 컴포넌트가 그려지며 자동으로 삭제
- api interceptor 초기화에 설명 주석 추가

index.html에 progress UI 추가, api interceptor 초기화에 설명 주석 추가

---

src/templates/MeetingView/Dropdown/styled.tsx

closes #238 
- Safari에서 버튼 기본색상이 파란색으로 변하는 것 방지

설정 버튼 색상을 black으로 지정

---

src/pages/MeetingResult.tsx

closes #236 
- meeting name이 길어질 경우 상위 요소가 길어지며 축하합니다 문구가 왼쪽으로 치우치는 이슈
축하합니다 문구가 항상 중앙에 정렬되게 수정

결과페이지 축하합니다 문구 중앙정렬 추가

---

src/components/CenterContentModal.tsx
src/components/Chip/styled.ts
src/components/MaskingInput.tsx
src/components/Progress.tsx
src/components/ShareButton.tsx
src/components/ShareDialog/ShareDialog.tsx
src/components/UserList/styled.ts
src/components/VoteTable/styled.tsx
src/components/buttons/ResultPageButton.tsx
src/components/buttons/VotePageButton.tsx
src/components/pageLayout.tsx
src/components/styled.tsx
src/pages/MeetingConfirm.tsx
src/pages/MeetingResult.tsx
src/pages/MeetingView.tsx
src/pages/MeetingVote.tsx
src/templates/MeetingEdit/CreatePasswordModal.tsx
src/templates/MeetingEdit/MeetingEditStepper.tsx
src/templates/MeetingEdit/MeetingEditTemplate.tsx
src/templates/MeetingEdit/SelectDates.tsx
src/templates/MeetingEdit/SelectMeetingType.tsx
src/templates/MeetingEdit/styled.tsx
src/templates/MeetingModify/styled.tsx
src/templates/MeetingResult/styled.tsx
src/templates/MeetingView/CheckConfirmModal.tsx
src/templates/MeetingView/Dropdown/Dropdown.tsx
src/templates/MeetingView/Dropdown/styled.tsx
src/templates/MeetingView/InputPasswordModal.tsx
src/templates/MeetingView/InputUsernameModal.tsx
src/templates/MeetingView/styled.tsx

- mui가 트리셰이킹이 될수 있도록 작업
- 바벨로 할 수 있는거 같았는데 그냥 얼마 없어서 작업했습니다 :)
ex) `import { Button } from '@mui/material'` ->  `import Button from '@mui/material/Button'`
하나라도.. 있으면 이전과 똑같이 돌아가기 때문에 **꼭 참고 부탁드립니다.**
정확한 비교는 아닌거 같지만.. 우선 차이가 생각보다 있을 것으로 예상됩니다.
|as-is|to-be|
|-|-|
|<img width="791" alt="스크린샷 2023-11-18 오전 11 34 51" src="https://github.com/Team-Panopticon/TBD-client/assets/49264892/5f281996-f97d-4218-9020-9343b015eeb6">|<img width="862" alt="스크린샷 2023-11-18 오전 11 35 42" src="https://github.com/Team-Panopticon/TBD-client/assets/49264892/48bba128-56c8-4794-880f-7343cc1b6b11">|
close #248

feat: mui가 트리셰이킹 될 수 있도록 임포트문 변경

---

src/apis/utils.ts
src/pages/MeetingCreate.tsx

closes #229 
- Meeting 생성 페이지에서는 미팅 생성 시 최초 API를 호출하게 됨
- Cloud functions가 켜지지 않은 상태인 경우 cold start 발생하여 모임 생성 API 호출이 오래걸림 (미팅생성 + 미팅조회 5초)
- Meeting 생성 페이지 접속 직후에 warmUp API를 의도적으로 호출해서 모임정보를 작성하는 동안 cloud functions를 키고 cold start를 예방
https://github.com/Team-Panopticon/TBD-server/pull/50

미팅 생성 페이지에서 cold start 방지용 warmUpInstance 함수 호출

---

src/hooks/MeetingConfirm/useMeetingConfirmContents.ts
src/hooks/MeetingConfirm/useMeetingConfirmFooter.ts
src/pages/MeetingConfirm/MeetingConfirm.tsx
src/templates/MeetingConfirm/MeetingConfirmContents/index.tsx
src/templates/MeetingConfirm/MeetingConfirmFooter/index.tsx
src/templates/MeetingConfirm/MeetingConfirmHeader/index.tsx

- MeetingConfirm 페이지를 header, contents, footer로 분리했어요.
- useMeetingView를 사용하는 부분이 있는데 해당 부분은 나중에 MeetingView mr이 닫히면서 수정하겠습니다!

feat: MeetingConfirm 페이지를 header, contents, footer로 분리

---

src/app.tsx
src/pages/Welcome/Welcome.tsx
src/templates/MeetingEdit/styled.tsx

- welcome 페이지에 PageLayout 적용 제거
레이아웃이 적용되면 여백이 레이아웃의 여백이 적용되므로 배경 변경이 매우 번거로움
- as-is
- to-be

Welcome 페이지 모임만들기 버튼 좌우 흰 여백 제거

---

src/constants/meeting.ts
src/pages/MeetingView/MeetingView.tsx
src/pages/MeetingVote/MeetingVote.tsx

https://github.com/Team-Panopticon/TBD-client/assets/32405358/684a6567-9f13-4770-b2d5-75d6559d1092
scrollTop이나 clientHeight이 0.5 단위로 잡혀서 맨 밑으로 스크롤해도 scrollHeight보다 작음

소수점으로 scroll이 남을경우 맨 아래이지만 스크롤 버튼이 사라지지 않는 이슈 해결

---

src/hooks/MeetingView/useMeetingViewHeader.ts

- InputPasswordModal을 띄울때 자동으로 focus가 가야하는데, 잡히지 않는 이슈
- setTimeout으로 delay를 줄 경우 문제가 해결되어 workaround 처리

InputPasswordModal 에서 focus가 잘 잡히도록 렌더링을 살짝 지연시킴

---

src/pages/Welcome/Welcome.tsx
src/templates/MeetingEdit/styled.tsx

- welcome 페이지에 PageLayout을 적용하지 않으며 Footer의 sticky가 적용되지 않음
welcome 페이지의 Footer에 position fixed를 인라인 스타일로 적용

welcome 페이지 Footer 버튼이 고정되지 않는 이슈 수정

---

src/components/pageLayout.tsx

#288 이슈에서 하단버튼 이슈
- dvh 속성 사용해서 하단 주소창 제외하고 vh로 잡히도록 조정
- https://web.dev/blog/viewport-units

Safari에서 100vh 설정으로 인해서 하단버튼이 가려지는 이슈 해결

---

src/components/MeetingContentsSkeleton.tsx

closes #291 
- 유저네임 목록 상위 div의 너비를 100%, 유저네임 각각의 너비를 33%로 설정

Skeleton 유저네임 목록이 테두리를 벗어나는 이슈 수정
